// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhb1HVMEUC-V1ccMrq4sn8QzntOmme53k',
    appId: '1:908590504957:web:1d2ad4a0bf10c25ada9794',
    messagingSenderId: '908590504957',
    projectId: 'codeshastra-35825',
    authDomain: 'codeshastra-35825.firebaseapp.com',
    storageBucket: 'codeshastra-35825.appspot.com',
    measurementId: 'G-KBLDELXMGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJzC8ug4AnW6OHe0b_IOKXZaiQfHSuq9g',
    appId: '1:908590504957:android:e5ebcc4e24c0fb51da9794',
    messagingSenderId: '908590504957',
    projectId: 'codeshastra-35825',
    storageBucket: 'codeshastra-35825.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATbwTnS3ZgU4XcttNRlZPGxuBQz1igUJ8',
    appId: '1:908590504957:ios:0c5b5f21a21b23d5da9794',
    messagingSenderId: '908590504957',
    projectId: 'codeshastra-35825',
    storageBucket: 'codeshastra-35825.appspot.com',
    iosBundleId: 'com.example.codeshastra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATbwTnS3ZgU4XcttNRlZPGxuBQz1igUJ8',
    appId: '1:908590504957:ios:3c490884e8387946da9794',
    messagingSenderId: '908590504957',
    projectId: 'codeshastra-35825',
    storageBucket: 'codeshastra-35825.appspot.com',
    iosBundleId: 'com.example.codeshastra.RunnerTests',
  );
}
